language: python
sudo: false
branches:
only:
  - master
python:
    - 3.5
    - 3.6
env: 
    - PYSAL_PYPI=true
    - PYSAL_PYPI=false
matrix:
  allow_failures:
      - python: 3.5
        env: PYSAL_PYPI=false
      - python: 3.6
        env: PYSAL_PYPI=false
      - python: 3.7
        env: PYSAL_PYPI=false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal' && pip install libpysal;
        else echo 'testing git libpysal'; git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../;
    fi;
  - conda install --yes --file requirements.txt;
  - pip install -r requirements_dev.txt

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=spreg;
  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
            - dfolch@gmail.com
            - daniel.arribas.bel@gmail.com
            - weikang9009@gmail.com
            - carsonfarmer@gmail.com
            - tayoshan@gmail.com
            - marynia.kolak@gmail.com
            - jgaboardi@gmail.com
            - phil.stphns@gmail.com
        on_success: change
        on_failure: change

after_success:
  - coveralls
